### ISSUE TITLE
material.angular.io fails to upgrade

### ISSUE THREAD

**Issue by amcdnl** [mgechev/rxjs-migrate#1]
When I run this on material.angular.io site (https://github.com/angular/material.angular.io), it gives the following error:

```
./node_modules/.bin/tslint -c migrate-rxjs.tslint.json --project src/tsconfig.json --fix
Warning: The 'migrate-to-pipeable-operators' rule requires type checking
/Users/austin/dev/material.angular.io/node_modules/tslint/lib/runner.js:118
            throw error;
            ^

TypeError: Cannot read property 'apply' of undefined
    at /Users/austin/dev/material.angular.io/node_modules/tslint/lib/language/rule/rule.js:28:66
    at Array.reduce (<anonymous>)
    at Function.Replacement.applyAll (/Users/austin/dev/material.angular.io/node_modules/tslint/lib/language/rule/rule.js:28:29)
    at Function.Fix.applyAll (/Users/austin/dev/material.angular.io/node_modules/tslint/lib/language/rule/rule.js:88:28)
    at Linter.lint (/Users/austin/dev/material.angular.io/node_modules/tslint/lib/linter.js:92:41)
    at Runner.processFiles (/Users/austin/dev/material.angular.io/node_modules/tslint/lib/runner.js:161:20)
    at Runner.run (/Users/austin/dev/material.angular.io/node_modules/tslint/lib/runner.js:110:18)
    at Object.<anonymous> (/Users/austin/dev/material.angular.io/node_modules/tslint/lib/tslint-cli.js:139:6)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
```

**Comment by mgechev** [comment]
A newer version of tslint should do the job. Tried it with 5.9.1 and it worked properly.
